services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '9001:9001'
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_BASE_URL=${VITE_BASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:9001/health']
      interval: 30s
      timeout: 10s
      retries: 3

  # Add development service for local development
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_BASE_URL=${VITE_BASE_URL}
    command: npm run dev
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:5173']
      interval: 30s
      timeout: 10s
      retries: 3
