export const CODE_LANGUAGES = {
  js: 'JavaScript',
  jsx: 'JavaScript (React)',
  ts: 'TypeScript',
  tsx: 'TypeScript (React)',
  python: 'Python',
  css: 'CSS',
  html: 'HTML',
  bash: 'Bash',
  json: 'JSON',
  yaml: 'YAML',
  md: 'Markdown',
  sql: 'SQL',
  graphql: 'GraphQL',
  rust: 'Rust',
  go: 'Go',
  java: 'Java',
  csharp: 'C#',
  php: 'PHP',
} as const;
