export const DEFAULT_QUESTION_CATEGORIES = [
  'Arrays',
  'Strings',
  'Hash Table',
  'Dynamic Programming',
  'Math',
  'Greedy',
  'Depth-First Search',
  'Breadth-First Search',
  'Binary Search',
  'Two Pointers',
  'Stack',
  'Queue',
  'Linked List',
  'Tree',
  'Graph',
  'Heap',
  'Bit Manipulation',
  'Backtracking',
  'Sliding Window',
  'Recursion',
  'Union Find',
  'Trie',
  'Design',
];
