name: Job Tracker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22, 23]
    steps:
      - uses: actions/checkout@v4

      - name: Installing bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - name: Install dependencies
        run: bun install

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Project
        run: bun run build

      - name: Eslint
        run: bun run lint:fix

      - name: Format
        run: bun run prettier:fix
