name: React Vite CI/CD

on:
  push:
    branches:
      - main # Trigger the action only on pushing to the main branch
  pull_request:
    branches:
      - main # Trigger the action for pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest # The runner environment (Ubuntu in this case)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Checkout the code from the repository

      - name: Set up Node.js 23.9.0
        uses: actions/setup-node@v3
        with:
          node-version: '23.9.0' # Specify Node.js version 23.9.0

      - name: Install pnpm
        run: |
          curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

      - name: Install Dependencies
        run: pnpm install # Install dependencies using pnpm

      - name: Build Project
        run: pnpm run build # Build your React Vite project using pnpm

      - name: Deploy to GitHub Pages
        if: success() # Only deploy if the build succeeds
        run: |
          pnpm add gh-pages --save-dev  # Add gh-pages if not already in dependencies
          pnpm run deploy  # Assuming you have a deploy script in your package.json

      - name: Upload Build Artifacts (Optional)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: vite-build
          path: dist # Path to your build directory (usually `dist` in Vite projects)
